### ISSUE TITLE
What is the difference between prom-analytics-proxy and vmauth?

### ISSUE THREAD

**Issue by denisgolius** [nicolastakashi/prom-analytics-proxy#106]
I mean [vmauth](https://docs.victoriametrics.com/vmauth/), and at first glance, they are  doing the same thing. See also https://grafana.com/grafana/dashboards/21394-victoriametrics-vmauth. vmauth supports PomQL and MetricsQL queries.

**Comment by nicolastakashi** [comment]
Hey @denisgolius 👋🏽

Thanks for sharing vmauth, I didn’t really know about this project.

I went through the vmauth documentation, and if I understood it correctly, it’s focused on other aspects like authorization, load-balancing, and query enforcement.

The prom-analytics-proxy is focused on expression analytics data to help engineers understand the shape of their PromQL expressions. For example:

1. What’s the most used expression.
2. What’s the most expensive PromQL expression in terms of samples and time taken.
3. What are the most common labels used in the expressions.

Does this answer your question?
